### ISSUE TITLE
Allow custom file path

### ISSUE THREAD

**Issue by moreiramarti** [IIBenII/backstage-plugin-dbt#243]
Hello,

Thank you for your reactivity about new backend system.
Do you think you could make file path customizable ?

I'm dealing with legacy docs and It could be tricky to move it.

Thanks,
Martinho

**Comment by IIBenII** [comment]
Hi,

All your docs are in the same backend technology (ie GCS or S3)? 

Having custom path can be easy to implement

**Comment by moreiramarti** [comment]
Yes, all in the same S3 bucket

**Comment by IIBenII** [comment]
Version 2.1.0 added this feature, thanks @sqsp-rwatkins for the work
