### ISSUE TITLE
dbtdoc-path in root bucket

### ISSUE THREAD

**Issue by moreiramarti** [IIBenII/backstage-plugin-dbt#254]
Hello, 

Me again :) 
Thanks for the last PR about custom path.

I'm still having an issue because my jsons are in the root of my bucket and last PR doesn't seem to allow that.

Do you think it's possible to allow it ?

Thanks

**Comment by IIBenII** [comment]
Hello @moreiramarti,

the latest version 2.2.0 allow to use `"."` as `dbtdoc-path` value
