### ISSUE TITLE
Section "Columns" empty

### ISSUE THREAD

**Issue by MiticoBerna** [IIBenII/backstage-plugin-dbt#271]
Hi,

thank you for your work!

Clicking on the "Details" button, of every "line", I have a problem, the "Columns" section is empty.
<img width="713" alt="Screenshot 2024-06-24 alle 16 40 48" src="https://github.com/IIBenII/backstage-plugin-dbt/assets/37406749/a10e7058-1139-4ab1-abed-47996a4127b7">

But with the built-in doc (dbt docs serve) I'm able to see the columns:
<img width="1048" alt="Screenshot 2024-06-24 alle 16 41 51" src="https://github.com/IIBenII/backstage-plugin-dbt/assets/37406749/14ee5773-bf4b-4158-865e-423619472d7a">

This is an extract of the json:
```
"nodes": {
  "model.model.test_model": {
    "config": {
      "column_types": {

      },
    },
    "description": "",
    "columns": {
      "country": {
        "name": "country",
        "description": "",
        "meta": {

        },
        "data_type": "STRING",
        "constraints": [],
        "quote": true,
        "tags": []
      },
      "transactionDate": {
        "name": "transactionDate",
        "description": "",
        "meta": {

        },
        "data_type": "DATE",
        "constraints": [],
        "quote": true,
        "tags": []
      },
      "bookingId": {
        "name": "bookingId",
        "description": "",
        "meta": {

        },
        "data_type": "STRING",
        "constraints": [],
        "quote": true,
        "tags": []
      },
      "transactionStatus": {
        "name": "transactionStatus",
        "description": "",
        "meta": {

        },
        "data_type": "STRING",
        "constraints": [],
        "quote": true,
        "tags": []
      },
      "value": {
        "name": "value",
        "description": "",
        "meta": {

        },
        "data_type": "FLOAT",
        "constraints": [],
        "quote": true,
        "tags": []
      },
    },
    "docs": {
      "show": true,
      "node_color": "green"
    },
    "build_path": null,
    "deferred": false,
  },
}
```

Could you please help me better understand why?

Thank you in advance

**Comment by IIBenII** [comment]
Hello,

Columns definition came from the file `catalog.json` maybe you can check in the file if you have columns for the model.

**Comment by MiticoBerna** [comment]
Hi @IIBenII,

thank you for your quick reply, I checked the catalog.json and it seems it's ok.
I rechecked Backstage and now I'm able to find the columns, maybe something goes wrong on my side.

Thanks again and sorry for the inconvenience.
